INSERT INTO departments (name, description) VALUES
('General Medicine', 'Provides diagnosis and treatment for adult patients with a wide range of medical conditions.'),
('General Surgery', 'Performs surgical procedures for various health conditions including abdominal and soft tissue operations.'),
('Emergency Medicine', 'Provides immediate care for patients with acute illness or injury requiring urgent attention.'),
('Intensive Care Unit (ICU)', 'Offers specialized care and monitoring for critically ill patients.'),
('Cardiology', 'Deals with disorders of the heart and circulatory system.'),
('Cardiothoracic Surgery', 'Performs surgical procedures on the heart, lungs, and chest cavity.'),
('Neurology', 'Diagnoses and treats diseases related to the nervous system.'),
('Neurosurgery', 'Performs surgeries involving the brain, spine, and peripheral nerves.'),
('Orthopedics', 'Manages conditions related to bones, joints, muscles, and ligaments.'),
('Pediatrics', 'Provides healthcare for infants, children, and adolescents.'),
('Neonatology', 'Specializes in medical care for newborn infants, especially premature ones.'),
('Obstetrics and Gynecology', 'Deals with women’s reproductive health, pregnancy, and childbirth.'),
('Urology', 'Focuses on the urinary tract system and male reproductive organs.'),
('Nephrology', 'Specializes in kidney-related diseases and dialysis care.'),
('Gastroenterology', 'Manages disorders of the digestive system.'),
('Hepatology', 'Focuses on diseases of the liver, gallbladder, biliary tree, and pancreas.'),
('Pulmonology', 'Deals with diseases involving the respiratory tract and lungs.'),
('Endocrinology', 'Treats hormonal and metabolic disorders such as diabetes and thyroid diseases.'),
('Rheumatology', 'Diagnoses and treats autoimmune and musculoskeletal diseases.'),
('Dermatology', 'Provides treatment for skin, hair, and nail disorders.'),
('Ophthalmology', 'Focuses on the diagnosis and treatment of eye diseases.'),
('ENT (Otorhinolaryngology)', 'Manages diseases related to the ear, nose, and throat.'),
('Dentistry', 'Provides oral and dental care.'),
('Oncology', 'Deals with prevention, diagnosis, and treatment of cancer.'),
('Hematology', 'Focuses on blood disorders and related systems.'),
('Radiology and Imaging', 'Uses imaging techniques like X-rays, CT scans, and MRIs for diagnosis and treatment.'),
('Pathology and Laboratory Medicine', 'Analyzes tissues, blood, and other samples for disease diagnosis.'),
('Anesthesiology', 'Provides anesthesia and pain management during surgeries and medical procedures.'),
('Psychiatry', 'Diagnoses and treats mental, emotional, and behavioral disorders.'),
('Psychology and Counseling', 'Offers therapy and counseling for mental health and emotional well-being.'),
('Physical Medicine and Rehabilitation', 'Helps restore function to patients with physical impairments.'),
('Nutrition and Dietetics', 'Provides dietary planning and nutrition counseling.'),
('Pharmacy', 'Dispenses medications and offers pharmaceutical guidance.'),
('Infectious Diseases', 'Specializes in diagnosis and management of infectious diseases.'),
('Geriatrics', 'Focuses on healthcare for elderly patients.'),
('Plastic and Reconstructive Surgery', 'Performs aesthetic and reconstructive surgeries.'),
('Burns Unit', 'Provides specialized care for patients with burn injuries.'),
('Trauma and Accident Care', 'Handles emergency cases involving accidents and severe injuries.'),
('Pain Management', 'Offers therapies and interventions to manage chronic pain.'),
('Occupational Therapy', 'Helps patients regain daily life skills after illness or injury.'),
('Speech and Hearing Therapy', 'Assists patients with speech, language, and hearing disorders.'),
('Palliative Care', 'Provides comfort and support to patients with life-limiting illnesses.'),
('Biomedical Engineering', 'Maintains and manages medical equipment and technology systems.'),
('Administration and Medical Records', 'Handles hospital administration, patient records, and health information systems.'),
('Blood Bank and Transfusion Medicine', 'Collects, stores, and provides blood and blood products for transfusion.');
